variables:
  DEPLOYABLE: 'false'

include:
- project: 'secata-public/pom/shared-ci'
  file: 'contract-java-test.yml'
  ref: 'par-8738_update-CI-to-2.10.0'
- project: 'secata-public/pom/shared-ci'
  file: 'rust-contract.yml'
  ref: 'par-8738_update-CI-to-2.10.0'
