image: registry.gitlab.com/partisia/dockerimages/rustmaven:1.67

stages:
- build

build:
  stage: build
  script:
  - cargo install cargo-partisia-contract
  - cargo partisia-contract build --release

codequality:
  stage: build
  except:
  - main
  script:
  - cargo check
  - cargo clippy --all-targets --all-features -- -D warnings -D missing_docs
  - cargo fmt --all -- --check
